import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Edit Bridge | Auth 🔐",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="bg-[url('/bg/auth.png')] bg-cover bg-no-repeat bg-center">{children}</div>;
}
