import { Navbar, Sidebar } from "@/components/layout";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative flex">
      <Sidebar />
      <main className="relative w-full">
        <Navbar />
        <div className="mt-[72px] p-4 pt-10">{children}</div>
      </main>
    </div>
  );
}
